import type { Metadata } from "next";
import { ThemeContextProvider } from "./lib/contexts/ThemeContext";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/footer/Footer";
import AuthProvider from "./providers/AuthProvider";

export const metadata: Metadata = {
  title: "GDG Cochabamba's Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ThemeContextProvider>
            <Navbar />
            {children}
            <Footer />
          </ThemeContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
