name: Deploy to Vercel
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Env Vars on Vercel Project
        uses: dkershner6/vercel-set-env-action@v1
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          # teamId: ${{ secrets.VERCEL_TEAM_ID }} # optional, without will use personal
          projectName: gdg-blog # project name in Vercel
          envVariableKeys: DATABASE_URL,NEXTAUTH_URL,GOOGLE_CLIENT_ID,GOOGLE_CLIENT_SECRET,GITHUB_CLIENT_ID,GITHUB_CLIENT_SECRET
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TARGET_DATABASE_URL: preview,development,production
          TYPE_DATABASE_URL: encrypted
          NEXTAUTH_URL: https://gdg-blog.vercel.app
          TARGET_NEXTAUTH_URL: preview,development,production
          TYPE_NEXTAUTH_URL: encrypted
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          TARGET_GOOGLE_CLIENT_ID: preview,development,production
          TYPE_GOOGLE_CLIENT_ID: encrypted
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          TARGET_GOOGLE_CLIENT_SECRET: preview,development,production
          TYPE_GOOGLE_CLIENT_SECRET: encrypted
          GITHUB_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
          TARGET_GITHUB_CLIENT_ID: preview,development,production
          TYPE_GITHUB_CLIENT_ID: encrypted
          GITHUB_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}
          TARGET_GITHUB_CLIENT_SECRET: preview,development,production
          TYPE_GITHUB_CLIENT_SECRET: encrypted

      # - name: Create .env file
      #   run: |
      #     echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
      #     echo "NEXTAUTH_URL=https://gdg-blog.vercel.app" >> .env
      #     echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
      #     echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
      #     echo "GITHUB_CLIENT_ID=${{ secrets.GH_CLIENT_ID }}" >> .env
      #     echo "GITHUB_CLIENT_SECRET=${{ secrets.GH_CLIENT_SECRET }}" >> .env

      - uses: amondnet/vercel-action@v20 #deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.ORG_ID}} #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
          vercel-args: "--prod"
